name: CI Java Checkstyle

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Checkstyle
    steps:
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@0.6.0
        # https://github.com/nikitasavinov/checkstyle-action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: 'checkstyle'


# checkstyle_config: src/main/resources/checkstyle.xml
# checkstyle_version: '10.3.1'
# fail_on_error: 'true'
# level: 'error'
# workdir: 'src/'
